= Preface

== Purpose

This document contains the design specifications of the Guideline Definition Language version 2 (GDL2). GDL2 is a formal language for expressing decision support logic. It is designed to be agnostic to languages, reference terminologies and standard EHR models. GDL2 is a major evolution from {openehr_cds_gdl}[GDL version 1^] ('GDL').

== Related Documents

Prerequisite documents for reading this document include:

* The {openehr_overview}[openEHR Architecture Overview^].
* {openehr_rm}[openEHR Reference Model specifications^].
* {openehr_cds_gdl}[GDL version 1^].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_cds_latest_gdl2}[{openehr_cds_latest_gdl2}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_technical_list}[technical mailing list^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== A Note on Nomenclature

This specification uses the terms 'GDL2' and 'GDL' to refer to version 2 of GDL, i.e. the formalism described in this specification.

== Resources

The {gdl_lang_site}[GDL-lang site^] is a useful location for GDL-related research material. The {gdl_models_github}[GDL Github repository^] contains published GDLguidelines. The {gdl_wiki}[GDL wiki^] provides further material.

== Changes since GDL version 1 ('GDL')

GDL2 introduces the following changes with respect to the original release of GDL:

* Data binding agnostic to EHR data models (e.g. openEHR / ISO13606 / FHIR);
* Template definition for output objects with new `use_template` statement with template-level variables; this enables, for example CDS-Hooks Cards & Suggestions as result of rule executions;
* Individual references and ability to reference to specific items in the rules;
* More math functions support.

Migration of GDL1 to GDL2 guidelines is described on the {gdl2_migration_tutorial}[gdl-lang site^].