= Reporting

The actions performed when a GDL2 rule is fired consist of statements, which may be assignments, procedure calls, or assertions. Assignments result in a value being set in a location of an output data set. In order to perform more processing with the result, procedures known to the execution engine may be called which will cause the computed results to be passed outside the GDL2 execution environment.

The following example shows a rule whose `then` action list includes the statement `use_template($gt2022)`. The code `gt2022` refers to a reporting 'template', which appears below the rule that mentions it. Within this template, the `object` field contains a structure whose model is defined by the preceding `model_id` and `template_id` attributes. Within the object structure, any output variables from the Guideline may be mentioned using the syntax `{}`, which means that at execution time, if the rule is fired, the template will be evaluated such that all `{}` mentions are substituted with their variable values, before final processing of the template (which might for example send it to a specific receiver service or application).

[source,json]
----
    "rules": {
      "gt0007": {
        "id": "gt0007",
        "priority": 1,
        "when": [...],
        "then": [
          "$gt0009|card.summary|='tTG serological testing is recommended'",
          "use_template($gt2022)"
        ]
      }

    "templates": {
      "gt2022": {
        "id": "gt2022",
        "name": "coeliac-disease-alert",
        "model_id": "generic_model",
        "template_id": "generic_model",
        "object": {
          "cards": [
            {
              "summary": "{$gt0009}",
              "detail": "Found risk factor(s):{$gt0020}",
              "indicator": "warning",
              "source": {
                "label": "National Institute for Health and Care Excellence (NICE). Coeliac disease: recognition, assessment and management. 2015.",
                "url": "https://www.nice.org.uk/guidance/ng20"
              }
            }
          ]
        }
      }
    },
----