=== DATA_BINDING Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DATA_BINDING*

h|*Description*
2+a|The binding of list of elements from a selected archetype or template to local gt codes.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*archetype_id*: `String`
a|The ID of the archetype, from where the list of elements is selected.

h|*0..1*
|*template_id*: `String`
a|The ID of an optional template to be used for selecting elements.

h|*1..1*
|*domain*: `String`
a|The space in which the rule variables reside. The value can either be:

* `"INPUT"`: input data to the guideline, e.g. values retrieved from the EHR;
* `"OUTPUT"`: output value generated by Guideline Rule execution.

h|*0..1*
|*elements*: `Hash<String,ELEMENT>`
a|Map of element binding indexed by local gt codes.

h|*0..1*
|*predicate_statements*: `List<ASSERTION>`
a|List of predicates (constraints) that need to be fulfilled before the EHR queries can be performed.

TODO: I've set this to an ASSERTION type that explicitly points to a Boolean-returning Expression.
|===
