=== DATA_BINDING Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DATA_BINDING*

h|*Description*
2+a|A list of bindings of nodes for a data-set' - i.e. from the archetype (and optionally template) specified by `_archetype_id_` and `_template_id_` respectively, to guideline variables, each specified by an element binding.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*model_id*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|The identifier of the data-set model (i.e. archetype or other) from which the list of elements is selected.

h|*0..1*
|*template_id*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|The ID of an optional template to be used for selecting elements.

h|*0..1*
|*bindings*: `link:/releases/BASE/{base_release}/foundation_types.html#_hash_class[Hash^]<link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^],<<_element_class,ELEMENT>>>`
a|Map of variable binding indexed by identifying gt-code of the variable.

h|*0..1*
|*predicates*: `link:/releases/BASE/{base_release}/foundation_types.html#_list_class[List^]<link:/releases/CDS/{cds_release}/expression.html#_assertion_class[ASSERTION^]>`
a|Predicates (constraints) that need to be satisfied before rule execution can occur. Generally speaking, predicates are constraints on variable values, and can only mention gt-codes of variables.

h|*1..1*
|*type*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Marker to indicate whether variable is an input or output variable in the data-set. The value can either be:

* `"INPUT"`: input data to the guideline, e.g. values retrieved from the EHR;
* `"OUTPUT"`: output value generated by Guideline Rule execution.
|===
