=== GUIDE_DEFINITION Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*GUIDE_DEFINITION*

h|*Description*
2+a|The definition of the guideline includes:

* `_pre_conditions_`: conditions defining the applicability of this guideline to a subject;
* `_data bindings_`: bindings to to archetypes and other sources;
* `_rules_`: define the logic of the guideline;
* `_template_`: defines the output reporting structure.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*data_bindings*: `Hash<String,DATA_BINDING>`
a|List of archetype bindings, which define specific elements to be used by rules.

h|*0..1*
|*pre_conditions*: `List<EXPRESSION_ITEM>`
a|List of pre-conditions to be met before the guide should be executed.

h|*0..1*
|*rules*: `Hash<String,RULE>`
a|Map of rules indexed by local gt codes.

h|*0..1*
|*default_actions*: `List<ASSIGNMENT>`
a|Actions that will always be performed, whenever the `_when_` conditions are evaluated, regardless of the result.

h|*0..1*
|*templates*: `Hash<String,OUTPUT_TEMPLATE>`
a|

h|*0..1*
|*internal_variables*: `List<LOCAL_VARIABLE>`
a|
|===
