=== GUIDELINE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*GUIDELINE*

h|*Description*
2+a|Representation of a discrete guideline, which defines archetype bindings, rules and descriptive meta-data.

h|*Inherit*
2+|`link:/releases/BASE/{cds_release}/resource.html#_authored_resource_class[AUTHORED_RESOURCE^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*id*: `link:/releases/BASE/{cds_release}/foundation_types.html#_string_class[String^]`
a|Identification of this guideline. Syntax is a string of format:

* `concept_name '.v' [N[.M.P]]`

For example: `calculate_bmi.v1`.

h|*0..1*
|*gdl_version*: `link:/releases/BASE/{cds_release}/foundation_types.html#_string_class[String^]`
a|The version of the GDL the guide is written in, in a string of format:

* `N.M[.P]`

i.e. a 2- or 3-number form of version, e.g. "1.0", "2.0", etc.

h|*1..1*
|*concept*: `link:/releases/BASE/{cds_release}/foundation_types.html#_string_class[String^]`
a|The normative meaning of the guideline as whole. Expressed as a gt-code.

h|*1..1*
|*definition*: `<<_guideline_definition_class,GUIDELINE_DEFINITION>>`
a|The main definition part of the guide. It consists of archetype bindings and rule definitions.

h|*1..1*
|*terminology*: `link:/releases/CDS/{cds_release}/terminology.html#_terminology_class[TERMINOLOGY^]`
a|Terminology definitions of the guideline containing definitions and translations (if applicable) for every gt-code.
|===
