=== GUIDELINE Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*GUIDELINE*

h|*Description*
2+a|Representation of a discrete guideline, which defines archetype bindings, rules and descriptive meta-data.

h|*Inherit*
2+|`AUTHORED_RESOURCE`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*id*: `String`
a|Identification of this guide.

TODO: details

h|*0..1*
|*gdl_version*: `String`
a|The version of the GDL the guide is written in.

h|*1..1*
|*concept*: `String`
a|The normative meaning of the guide as whole. Expressed as a local guide code.

h|*1..1*
|*definition*: `GUIDE_DEFINITION`
a|The main definition part of the guide. It consists of archetype bindings and rule definitions.

h|*1..1*
|*terminology*: `ARCHETYPE_TERMINOLOGY`
a|TBD: I wonder if we should just reference the AM Terminology class here for now - it makes it easy to show re-use; or do you prefer just to make a local custom one for now? I have done it using a ref to AM::ARCHETYPE_TERMINOLOGY just to show how it looks. I think this could be better from a spec POV, I would not change anything in your impl, it is close enough.

h|*1..1*
|*test_cases*: 
a|TBD: need a better understanding of this.
|===
