include::partial$module_vars.adoc[]

= Appendix


== Acknowledgements

=== Primary Author

* Rong Chen MD, PhD, Cambio CDS, Sweden

=== Contributors

This specification has benefited from formal and informal input from the openEHR and wider health informatics community. The openEHR Foundation would like to recognise the following people for their contributions.

* Thomas Beale, Ars Semantica (UK); openEHR Foundation Management Board.

=== Support

The work to produce this specification was funded by the following organisations:

* Cambio CDS, Sweden.

=== Trademarks

* 'openEHR' is a trademark of the openEHR Foundation
* 'Java' is a registered trademark of Oracle Corporation
* 'Microsoft' and '.Net' are trademarks of the Microsoft Corporation
== A Note on Nomenclature

This specification uses the terms 'GDL2' and 'GDL' to refer to version 2 of GDL, i.e. the formalism described in this specification.

== Resources

The {gdl_lang_site}[GDL-lang site^] is a useful location for GDL-related research material. The {gdl_models_github}[GDL Github repository^] contains published GDLguidelines. The {gdl_wiki}[GDL wiki^] provides further material.

== Changes since GDL version 1 ('GDL')

GDL2 introduces the following changes with respect to the original release of GDL:

* Data binding agnostic to EHR data models (e.g. openEHR / {iso_13606}[ISO 13606^] / {hl7_fhir}[HL7 FHIR^]);
* Template definition for output objects with new `use_template` statement with template-level variables; this enables, for example CDS-Hooks Cards & Suggestions as result of rule executions;
* Individual references and ability to reference to specific items in the rules;
* More math functions support.

Migration of GDL1 to GDL2 guidelines is described on the {gdl2_migration_tutorial}[gdl-lang site^].

:sectnums!:

include::partial$amendment_record.adoc[]
