= Preface

== Purpose

This document contains the design specifications of the Guideline Definition Language (GDL). GDL is a formal language for expressing decision support logic. It is designed to be agnostic to natural languages and reference terminologies by leveraging the designs of openEHR Reference Model and Archetype Model.

== Related Documents

Prerequisite documents for reading this document include:

* {openehr_rm}[openEHR Reference Model specifications].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_cds_gdl}[{openehr_domain}/releases/CDS/latest/GDL.html].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

Users are encouraged to comment on and/or advise on these paragraphs as well as the main content.  Feedback should be provided either on the {openehr_technical_list}[technical mailing list], or on the {openehr_jira_prs_cds}[specifications issue tracker].


