= Preface

== Purpose

This document contains the design specifications of the Guideline Definition Language (GDL). GDL is a formal language for expressing decision support logic. It is designed to be agnostic to natural languages and reference terminologies by leveraging the designs of openEHR Reference Model and Archetype Model.

== Related Documents

Prerequisite documents for reading this document include:

* {openehr_rm}[openEHR Reference Model specifications^].

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {openehr_cds_gdl}[{openehr_cds_gdl}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

== Feedback

Feedback may be provided on the {openehr_technical_list}[technical mailing list^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

